# Generated by Django 2.1.7 on 2019-03-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryTitle', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='evaluate_rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric', models.CharField(max_length=200)),
                ('grade_score', models.FloatField()),
                ('student', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measureTitle', models.CharField(default='', max_length=200, null=True)),
                ('measureText', models.CharField(blank=True, max_length=200, null=True)),
                ('cutoff_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('cutoff_score', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('cycle', models.ManyToManyField(to='main.Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('title', models.CharField(blank=True, default='Untitled', max_length=200, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=200)),
                ('assigned_to', models.ManyToManyField(to='main.Evaluator')),
                ('category', models.ManyToManyField(to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_name', models.CharField(default='Test', max_length=200, primary_key=True, serialize=False)),
                ('created_by', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Test_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=200, null=True)),
                ('score', models.PositiveIntegerField()),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Test')),
            ],
        ),
        migrations.AddField(
            model_name='measure',
            name='outcome',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Outcome'),
        ),
        migrations.AddField(
            model_name='measure',
            name='rubric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rubric'),
        ),
        migrations.AddField(
            model_name='measure',
            name='test_score',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Test_score'),
        ),
    ]
