# Generated by Django 2.1.1 on 2019-04-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index_x',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='index_y',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
