# Generated by Django 2.1.1 on 2019-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubric',
            old_name='learning_outcome',
            new_name='category',
        ),
        migrations.AddField(
            model_name='rubric',
            name='measure',
            field=models.CharField(default='nada', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubric',
            name='measureText',
            field=models.CharField(default='nada', max_length=200),
            preserve_default=False,
        ),
    ]
