# Generated by Django 2.1.7 on 2019-04-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190330_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rubric'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rubric'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='test_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Test'),
        ),
    ]
