# Generated by Django 2.1.1 on 2019-02-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190225_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='weight',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
