# Generated by Django 2.1.1 on 2019-04-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190403_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='evaluator',
            field=models.ManyToManyField(to='main.Evaluator'),
        ),
        migrations.AddField(
            model_name='measure',
            name='student',
            field=models.ManyToManyField(to='main.Student'),
        ),
    ]
