# Generated by Django 2.1.1 on 2019-03-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190327_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
