# Generated by Django 2.1.1 on 2019-02-25 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190225_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluate_rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluator', models.CharField(max_length=200)),
                ('grade_score', models.PositiveIntegerField()),
                ('student', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='rubric',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='evaluate_rubric',
            name='rubric',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Rubric'),
        ),
    ]
