# Generated by Django 2.1.1 on 2019-03-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190327_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measureTitle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='title',
            field=models.CharField(default=1.1, max_length=200),
            preserve_default=False,
        ),
    ]
