# Generated by Django 2.1.1 on 2019-04-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190403_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='endDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='cycle',
            name='isCurrent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='startDate',
            field=models.DateField(default=None),
        ),
    ]
