# Generated by Django 2.1.1 on 2019-03-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190327_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measureText',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
