# Generated by Django 2.1.1 on 2019-04-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190404_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='endDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
