# Generated by Django 2.1.1 on 2019-03-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190327_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measureText',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='measure',
            name='measureTitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
