# Generated by Django 2.1.1 on 2019-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190405_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_score',
            name='test',
            field=models.CharField(blank=True, default='Test', max_length=200, null=True),
        ),
    ]
