# Generated by Django 2.1.1 on 2019-02-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190225_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubric',
            name='measure',
        ),
        migrations.AddField(
            model_name='rubric',
            name='measure',
            field=models.ManyToManyField(to='main.Measure'),
        ),
    ]
