# Generated by Django 2.1.1 on 2019-04-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190406_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='test_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Test_score'),
        ),
    ]
