# Generated by Django 2.1.1 on 2019-04-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190406_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate_rubric',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Measure'),
        ),
    ]
