# Generated by Django 2.1.1 on 2019-02-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190226_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluate_rubric',
            name='grade_score',
            field=models.FloatField(),
        ),
    ]
