# Generated by Django 2.1.1 on 2019-04-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_evaluate_rubric_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluate_rubric',
            name='evaluated_by',
            field=models.CharField(default='Dr. smith', max_length=200),
            preserve_default=False,
        ),
    ]
