# Generated by Django 2.1.1 on 2019-04-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_measure_measuretext'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='status',
            field=models.CharField(choices=[('passing', 'passing'), ('failing', 'failing'), ('passed', 'passed'), ('failed', 'failed')], default='failing', max_length=100),
        ),
    ]
