# Generated by Django 2.1.1 on 2019-04-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_measure_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='perc_completed',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
