# Generated by Django 2.1.1 on 2019-03-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='outcomes',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='rubrics',
        ),
    ]
