# Generated by Django 2.2 on 2019-04-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_evaluator_perc_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='isWeighted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
