# Generated by Django 2.1.7 on 2019-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rubric_isweighted'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluate_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluated', models.BooleanField(default=False, null=True)),
                ('evaluator', models.ManyToManyField(to='main.Evaluator')),
                ('measure', models.ManyToManyField(to='main.Measure')),
            ],
        ),
    ]
