# Generated by Django 2.1.1 on 2019-03-13 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_evaluator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='email',
        ),
    ]
