# Generated by Django 2.1.1 on 2019-04-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rubric_isweighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='statusPercent',
            field=models.FloatField(default=0.0),
        ),
    ]
