# Generated by Django 2.1.7 on 2019-04-15 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_evaluate_student'),
        ('main', '0016_measure_statuspercent'),
    ]

    operations = [
    ]
