# Generated by Django 2.1.1 on 2019-03-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_evaluator_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluator',
            name='user',
        ),
        migrations.AddField(
            model_name='evaluator',
            name='email',
            field=models.CharField(default='def', max_length=200),
            preserve_default=False,
        ),
    ]
