# Generated by Django 2.1.1 on 2019-04-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_measure_statuspercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='evaluationPercent',
            field=models.FloatField(default=0.0),
        ),
    ]
