# Generated by Django 2.1.1 on 2019-04-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_measure_evaluationpercent'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluator',
            name='invited_by',
            field=models.CharField(default='Admin', max_length=200),
        ),
    ]
