# Generated by Django 2.1.7 on 2019-04-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20190415_0306'),
        ('main', '0019_evaluation_flag'),
    ]

    operations = [
    ]
