# Generated by Django 2.1.7 on 2019-04-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_custom_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='ascending',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
