# Generated by Django 2.1.7 on 2019-04-16 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_merge_20190416_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='custom_students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('graded', models.BooleanField(default=False, null=True)),
                ('grade', models.FloatField(null=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Evaluator')),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Measure')),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluate_student',
            name='evaluator',
        ),
        migrations.RemoveField(
            model_name='evaluate_student',
            name='measure',
        ),
        migrations.DeleteModel(
            name='evaluate_student',
        ),
    ]
