# Generated by Django 2.1.1 on 2019-04-19 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rubric_ascending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=400)),
                ('sent_at', models.DateTimeField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
