# Generated by Django 2.1.1 on 2019-04-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('credit_hours', models.PositiveIntegerField(default=3)),
            ],
        ),
        migrations.AddField(
            model_name='outcome',
            name='course',
            field=models.ManyToManyField(to='main.Course'),
        ),
    ]
