# Generated by Django 2.1.1 on 2019-04-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20190418_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_students',
            name='type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
