# Generated by Django 2.1.7 on 2019-04-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='category_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=400, null=True)),
                ('score', models.CharField(max_length=200, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.custom_students')),
            ],
        ),
    ]
