# Generated by Django 2.1.7 on 2019-04-23 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_custom_students_current'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoOrdinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cycle',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CoOrdinator'),
        ),
        migrations.AddField(
            model_name='evaluator',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CoOrdinator'),
        ),
        migrations.AddField(
            model_name='measure',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CoOrdinator'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CoOrdinator'),
        ),
        migrations.AddField(
            model_name='rubric',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CoOrdinator'),
        ),
    ]
