# Generated by Django 2.1.1 on 2019-04-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_outcome_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryTitle',
            field=models.CharField(max_length=600),
        ),
    ]
