# Generated by Django 2.1.1 on 2019-04-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190425_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invited_Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=200)),
                ('invited_by', models.CharField(max_length=200)),
            ],
        ),
    ]
