# Generated by Django 2.1.1 on 2019-04-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_invited_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='invited_coordinator',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
