# Generated by Django 2.1.7 on 2019-04-28 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_invited_coordinator_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CoOrdinator'),
        ),
    ]
