# Generated by Django 2.1.7 on 2019-04-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_course_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedCo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
    ]
