# Generated by Django 2.1.1 on 2019-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_invitedco'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to',
            field=models.CharField(default='no one', max_length=200),
        ),
    ]
