# Generated by Django 2.1.7 on 2019-05-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20190430_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitedco',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
