# Generated by Django 2.1.7 on 2019-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_invitedco_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='status',
            field=models.CharField(choices=[('passing', 'passing'), ('failing', 'failing'), ('passed', 'passed'), ('failed', 'failed')], default='pending', max_length=100),
        ),
    ]
