# Generated by Django 2.1.7 on 2019-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20190501_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='status_help',
            field=models.CharField(default='pending', max_length=200, null=True),
        ),
    ]
