# Generated by Django 2.1.1 on 2019-05-04 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_log_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_score',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Measure'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='status',
            field=models.CharField(choices=[('passing', 'passing'), ('failing', 'failing'), ('passed', 'passed'), ('failed', 'failed')], default='notstarted', max_length=100),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='status_help',
            field=models.CharField(default='notstarted', max_length=200, null=True),
        ),
    ]
