# Generated by Django 2.1.1 on 2019-05-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20190503_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_score',
            name='measure',
        ),
    ]
